name: Test Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo bah
      - run: echo ${{ github.event.event_name }}
  test-2:
    runs-on: ubuntu-latest
    steps:
      - run: echo buuu