name: Test Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo bah
      - run: echo "${{ toJson(github.event) }}"
  test-2:
    needs: test-1
    runs-on: ubuntu-latest
    steps:
      - run: echo buuu